return {
    schema=1,
    id='sortie-objective-b-weapon-skill-v1',version='1.0.0',
    policy_id='pt-sortie-b-ws',
    label='Sortie B: automatic Biune weapon-skill credit',
    aliases={'bws','sortie-b-ws','biune-ws'},runtime_owns_pull=true,
    -- Explicit recovery profile only. sortie-main-v1 owns automatic Sortie
    -- target routing so this profile can never replace it on a target packet.
    gearswap_adapter={
        id='sortie-objective-b-weapon-skill-v1',version='1.0.0',
        controller='sortie-b-ws',protocol=1,
        actions={'savage-blade','evisceration','black-halo','cancel'},
    },
    members={
        Dolomedes={main_job='COR',sub_jobs={'DNC','NIN','DRK'}},
        Tackleberry={main_job='PLD',sub_jobs={'SCH','WAR','BLU','WHM'}},
        Kickpuncher={main_job='DNC',sub_jobs={'WAR','NIN','DRG'}},
        Barneystinson={main_job='BRD',sub_jobs={'WHM','NIN','DRK'}},
        Smalls={main_job='RDM',sub_jobs={'WHM','BLM','DRK'}},
        Achoo={main_job='GEO',sub_jobs={'WHM','BLM','DRK'}},
    },
    roles={route_leader='Dolomedes',tank='Tackleberry',
        manual_puller='Tackleberry',target_caller='Dolomedes',
        finisher='Dolomedes',backup_healer='Kickpuncher'},
    combat={leader='Dolomedes',puller='Tackleberry',movement='mobile',
        attackers={'Dolomedes','Tackleberry','Kickpuncher',
            'Barneystinson','Smalls','Achoo'},
        targeters={'Dolomedes','Tackleberry','Kickpuncher',
            'Barneystinson','Smalls','Achoo'},
        priority_attackers={},target_exclusions={}},
    support={
        cor={rolls={'tactician','samurai'}},
        brd={preset='physical',target_source='Tackleberry',healbot='off'},
        rdm={preset='sortieacuex',target_source='Tackleberry',
            haste={'Tackleberry','Dolomedes','Kickpuncher','Smalls'},
            refresh={'Smalls','Achoo','Tackleberry'},
            phalanx={'Tackleberry'},defense={},healbot='off'},
        geo={mode='leanmanaged',zerg=false,indi='Fury',geo='Frailty',
            entrust='Refresh',entrustee='Smalls',
            combat_entrust_only=false,healbot='off'},
        pld={preset='locusbats',leader='Dolomedes'},
        dnc={preset='physical',target_source='Tackleberry'},
    },
    offense={
        Dolomedes={weapon_mode='DualSavage',ws='Savage Blade',tp=1000,
            automatic=false,disable_native_autows=true},
        Tackleberry={weapon_mode='Naegling',ws='Savage Blade',tp=1000,
            automatic=false,disable_native_autows=true},
        Kickpuncher={weapon_mode='Tauret',ws='Evisceration',tp=1000,
            automatic=false,disable_native_autows=true},
        Barneystinson={weapon_mode='Naegling',ws='Savage Blade',tp=1000,
            automatic=false,disable_native_autows=true},
        Smalls={weapon_mode='Maxentius',ws='Black Halo',tp=1000,
            automatic=false,disable_native_autows=true},
        Achoo={weapon_mode='Maxentius',ws='Black Halo',tp=1000,
            automatic=false,disable_native_autows=true},
    },
    preflight={required_before_combat=false,max_age_seconds=300,members={
        Dolomedes={controller={name='sortie-b-ws',protocol=1},actions={{kind='weaponskill',name='Savage Blade'}}},
        Tackleberry={controller={name='sortie-b-ws',protocol=1},actions={{kind='weaponskill',name='Savage Blade'}}},
        Kickpuncher={controller={name='sortie-b-ws',protocol=1},actions={{kind='weaponskill',name='Evisceration'}}},
        Barneystinson={controller={name='sortie-b-ws',protocol=1},actions={{kind='weaponskill',name='Savage Blade'}}},
        Smalls={controller={name='sortie-b-ws',protocol=1},actions={{kind='weaponskill',name='Black Halo'}}},
        Achoo={controller={name='sortie-b-ws',protocol=1},actions={{kind='weaponskill',name='Black Halo'}}},
    }},
    manual_actions={},safety={reraise=true},
    advisories={
        'Explicit recovery profile only; sortie-main-v1 owns automatic target handling. If deliberately loaded, Tackle is preferred for first threat and any party claim releases full burn.',
        'All six build TP quickly; near the finish the runtime stops melee and guarantees a verified ready weapon skill before the target dies. If it survives, damage resumes and the cycle repeats automatically.',
        'The first five credited targets earn Shard B for Leshonn. A later five can earn Metal B, but the main route stops after Shard B unless live evidence shows the extra safety is worth the time.',
        'Commands are recovery only. Manual movement, targets, and improvised actions remain available at every point.',
    },
}
