-- Canonical permanent traversal objectives from the local BGWiki mirror.
-- Combat objectives and boss mechanics will be separate immutable content.

return {
    key_a = {sector='A', reward='key_a',
        objective='Open any unlocked Gate #A.'},
    plate_a = {sector='A', reward='plate_a',
        objective='Cast any magic next to Diaphanous Device #A.'},
    sheet_a = {sector='A', reward='sheet_a',
        objective='Interact with Diaphanous Bitzer #A while actually naked.'},
    key_b = {sector='B', reward='key_b',
        objective='Open Gates #B1 through #B6 in exact order.'},
    plate_b = {sector='B', reward='plate_b',
        objective='Use /hurray while targeting Diaphanous Device #B.'},
    sheet_b = {sector='B', reward='sheet_b',
        objective='Reach Bitzer #B from the entrance on foot without a Device warp.'},
    key_c = {sector='C', reward='key_c',
        objective='Open Gate #C1 or #C2 before defeating anything in C.'},
    plate_c = {sector='C', reward='plate_c',
        objective='Defeat a Cachaemic foe next to Diaphanous Device #C.'},
    sheet_c = {sector='C', reward='sheet_c',
        objective='After a C kill, one player Materializes at Device C and that same player touches Bitzer C.'},
    key_d = {sector='D', reward='key_d',
        objective='Open Gate #D1 and #D2 within two minutes.'},
    plate_d = {sector='D', reward='plate_d',
        objective='DROP the Obsidian Wing at Device D; never use it.'},
    sheet_d = {sector='D', reward='sheet_d',
        objective='Defeat every regular Demisang, then touch Bitzer D.'},
    shard_a_magic = {sector='A', reward='shard_a',
        objective='Defeat three Abject foes with single-target magic killing blows.'},
    metal_a_magic = {sector='A', reward='metal_a',
        objective='After Shard A, defeat three more Abject foes with single-target magic killing blows.'},
    shard_b_weapon_skill = {sector='B', reward='shard_b',
        objective='Perform at least one weapon skill on each of five Biune foes before defeating it.'},
    metal_b_weapon_skill = {sector='B', reward='metal_b',
        objective='After Shard B, perform at least one weapon skill on each of five more Biune foes before defeating it.'},
    shard_c_burst = {sector='C', reward='shard_c',
        objective='Magic Burst on three Cachaemic foes before defeating each one.'},
    metal_c_burst = {sector='C', reward='metal_c',
        objective='After Shard C, Magic Burst on three more Cachaemic foes before defeating each one.'},
    boss_skomora = {sector='C', reward='shard_g',
        objective='Defeat Skomora and open its reward chest with the full party present.'},
    boss_ghatjot = {sector='A', reward='shard_e',
        objective='Defeat Ghatjot and open its reward chest with the full party present.'},
    boss_leshonn = {sector='B', reward='shard_f',
        objective='Defeat Leshonn and open its reward chest with the full party present.'},
}
