-- Live-replay route built from Dolomedes' 2026-09-10 Key-B / Sheet-D run.
-- Corridor points are display-only navigation hints. Every movement,
-- interaction, target choice, and override remains under operator control.

local zones = {
    [133]=true, [189]=true, [275]=true,
    [267]=true, [281]=true,
}

local function point(name, x, y, z, cue, confidence, radius)
    return {
        name=name, x=x, y=y, z=z,
        radius=radius or 10, z_tolerance=14,
        cue=cue,
        coordinate_semantics='captured_operator_path',
        confidence=confidence or 'high_live_capture',
    }
end

return {
    schema=1,
    id='sortie-key-b-sheet-d-canary-live',
    aliases={},
    version='2.0.0',
    title='Sortie: Key B then complete Demisang sweep',
    content='sortie',
    allowed_zones=zones,
    guide_only=false,

    -- These private points turn the arrow at corridor junctions instead of
    -- merely pointing through walls at a distant objective. The B path is
    -- reconstructed from the successful live run. The final unvisited D
    -- room centers are deliberately labelled provisional for next-run
    -- calibration; //exg wp and //exg next always override them.
    landmarks={
        kb_start_east=point('Start: east hall', -860, -20, -180,
            'Leave the entry room east; take the long hall north.'),
        kb_a_west_north=point('A west hall: north turn', -860, 100, -180,
            'Turn east at the top of the long hall.'),
        kb_a_east=point('A west rooms: east bend', -780, 100, -180,
            'Continue east, then bend north toward Gate A1.'),
        kb_a1_approach=point('Gate A1 approach', -800, 180, -172,
            'Open Gate A1 if closed; continue through it.'),
        kb_a1_exit=point('Beyond Gate A1', -784, 220, -172,
            'Turn west after the gate.'),
        kb_a_upper_west=point('Upper A: west junction', -860, 220, -180,
            'At the west junction, turn north.'),
        kb_a_upper_north=point('Upper A: north hall', -860, 320, -180,
            'Continue north, then take the east passage.'),
        kb_a2=point('Gate A2', -700, 378, -180,
            'Open Gate A2 if closed and pass through.'),
        kb_a2_exit=point('Beyond Gate A2', -680, 340, -180,
            'Turn east, then north into the upper hall.'),
        kb_a3_west=point('Gate A3 west approach', -580, 380, -180,
            'Continue east toward Gate A3.'),
        kb_a3=point('Gate A3', -500, 380, -180,
            'Open Gate A3 if closed; turn south beyond it.'),
        kb_a3_south=point('A3 south hall', -420, 240, -170,
            'Follow the hall south.'),
        kb_locked_a=point('Locked Gate A passage', -380, 128, -162,
            'Open Locked Gate A and continue south.'),
        kb_b_west_entry=point('B outer west hall', -300, 60, -170,
            'Turn east and stay on the outer route.'),
        kb_b_north_bend=point('B north bend', -220, 100, -180,
            'Continue east along the north hall; do not touch B3.'),
        kb_b1_north=point('B1 north approach', -60, 100, -182,
            'Turn south at the far-east junction.'),

        kb_b1_south=point('From B1: south hall', -60, 10, -182,
            'After B1, continue south.'),
        kb_b2_diagonal=point('B2 diagonal approach', -118, -37, -175,
            'Follow the southwest bend to B2.'),

        kb_b2_return=point('From B2: northeast return', -90, -15, -178,
            'Backtrack northeast.'),
        kb_b3_north=point('B3 north junction', -60, 100, -182,
            'Turn west, then north toward B3.'),
        kb_b3_turn=point('B3 final turn', -100, 115, -172,
            'Continue north to B3.'),

        kb_b3_exit=point('From B3: south return', -100, 110, -172,
            'Backtrack south, then take the west hall.'),
        kb_b4_west=point('B4 west hall', -220, 100, -172,
            'Turn south at the west junction.'),
        kb_b4_south=point('B4 south bend', -220, 62, -168,
            'Follow the southwest bend.'),
        kb_b4_diagonal=point('B4 diagonal approach', -282, 36, -164,
            'Continue southwest to B4.'),

        kb_b4_exit=point('From B4: west bend', -340, 20, -162,
            'Turn south.'),
        kb_b5_north=point('B5 north approach', -340, -40, -162,
            'Continue south to B5.'),

        kb_b5_east=point('From B5: east hall', -204, -60, -172,
            'Go east to the far junction.'),
        kb_b6_north=point('B6 route: north turn', -144, -18, -172,
            'Turn north, then immediately west.'),
        kb_b6_west=point('B6 route: west hall', -215, -20, -172,
            'Continue west, then turn north to B6.'),

        kb_device_west=point('Return toward Device B', -260, 24, -166,
            'From B6, go west toward the Device B room.'),
        kb_device_entry=point('Device B room entrance', -340, 20, -154,
            'Enter the room and use Device B.'),
        kd_c_west=point('From Device C: west hall', -500, -140, -154,
            'After teleporting to Device C, take the west passage.'),
        kd_entry=point('Sector D entrance', -500, -175, -162,
            'Pass through the D entrance and stop at the six-job party.'),

        d_entry_party=point('D room 1: entrance six', -500, -180, -162,
            'Clear all six jobs in this room.'),
        d_south_hall=point('D room 2: south hallway', -500, -280, -170,
            'Follow the south hall; clear every regular Demisang passed.'),
        d_upper_boss=point('D room 3: upper boss-side plaza', -500, -340, -178,
            'Clear the upper plaza and both sides before moving on.'),
        d_east_boss=point('D room 4: east boss-side branch', -460, -380, -182,
            'Clear the east branch, then return west.'),
        d_lower_boss=point('D room 5: lower boss-side plaza', -500, -420, -192,
            'Clear the lower plaza; ignore Deleterious unless desired.'),
        d_southwest_entry=point('D room 6: southwest passage', -580, -420, -190,
            'Take the west passage into the southwest rooms.'),
        d_southwest_gate=point('D room 7: Gate D1 side', -680, -380, -172,
            'Clear around Gate D1 and continue west.'),
        d_southwest_center=point('D room 8: southwest center', -760, -380, -176,
            'Clear the center of the southwest plaza.'),
        d_southwest_west=point('D room 9: southwest west branch', -840, -380, -180,
            'Clear the far-west branch, then turn north.'),
        d_southwest_north=point('D room 10: southwest north branch', -840, -280, -180,
            'Clear the north branch, then work back east.',
            'provisional_map_trace', 14),
        d_ring_west=point('D room 11: west side of square loop', -660, -276, -170,
            'Clear the west side of the square corridor.'),
        d_ring_north=point('D room 12: north side of square loop', -600, -260, -168,
            'Clear the north side, including its room.'),
        d_ring_east=point('D room 13: east side of square loop', -540, -214, -162,
            'Clear the east side and its branch.'),
        d_d2_south=point('D room 14: south of Gate D2', -540, -110, -162,
            'Clear the room south of D2, then turn west.'),
        d_d2_west=point('D room 15: D2 west plaza', -680, -88, -166,
            'Clear the entire west plaza before returning to D2.'),
        d_device_nw=point('D room 16: Device D northwest room', -660, 20, -154,
            'Clear the small room northwest of Device D.',
            'provisional_map_trace', 14),
        d_device_north=point('D room 17: Device D north plaza', -580, 100, -162,
            'Clear the full north plaza; check both sides.',
            'provisional_map_trace', 14),
        d_device_return=point('Return to Device D', -580, -20, -150,
            'Return to Device D after the final room audit.'),
    },

    run_transactions={
        {
            id='key_b_gate_sequence', rewind='b_gate_1',
            goal={kind='all_temp_item', item='key_b'},
        },
        {
            id='d_full_demisang_clear', rewind='d_opening_party',
            goal={kind='all_temp_item', item='sheet_d'},
        },
    },

    steps={
        {
            id='preentry', area='OUTSIDE',
            completion={kind='all_key_item', item='shiny_plate', auto=true},
            instruction='Get a Shiny Ra\'Kaznarian plate on all six, then gather at the Kamihr transposer.',
            warning='Key B is the first objective. Sheet D is optional use of remaining time, never an entry or success requirement.',
        },
        {
            id='enter', area='ENTRY', completion={kind='all_in_pack', auto=true},
            instruction='Dolo enters manually. Bring all six through the transposer and let them finish loading.',
            warning='The addon never enters, moves, targets, or interacts for you. Sensor warnings are advice; manual play remains available.',
        },
        {
            id='sensor_audit', area='START', waypoint='device_start',
            completion={kind='sensor_quorum', auto=true},
            instruction='Briefly gather at the starting Device while ExpeditionGuide receives fresh reports from all six.',
            warning='Do not wait on the addon if you need to move. //exg next always advances by operator override.',
        },
        {
            id='key_a_access', area='START',
            completion={kind='all_temp_item', item='key_a', auto=true},
            instruction='Confirm the party already has Key A access. The next step gives the full corridor route to B1.',
            warning='If the sensor cannot prove Key A but Dolo can open Locked Gate A, use //exg next and continue.',
        },
        {
            id='b_gate_1', area='TO B1',
            path={'kb_start_east','kb_a_west_north','kb_a_east',
                'kb_a1_approach','kb_a1_exit','kb_a_upper_west',
                'kb_a_upper_north','kb_a2','kb_a2_exit','kb_a3_west',
                'kb_a3','kb_a3_south','kb_locked_a','kb_b_west_entry',
                'kb_b_north_bend','kb_b1_north','gate_b1'},
            completion={kind='target_interaction',landmark='gate_b1',auto=true},
            instruction='Follow each corridor arrow to far-east Gate B1. Open A1/A2/A3 and Locked Gate A as needed, but do not touch B2-B6 yet. Interacting with B1 advances automatically.',
            warning='The B doors themselves must be opened B1 > B2 > B3 > B4 > B5 > B6. //exg wp skips a bad corridor point; //exg next overrides the whole step.',
            detail={'The arrow is turn-by-turn. It advances as Dolo reaches each corner; it never steers or blocks input.'},
        },
        {
            id='b_gate_2', area='B1 TO B2',
            path={'kb_b1_south','kb_b2_diagonal','gate_b2'},
            completion={kind='target_interaction',landmark='gate_b2',auto=true},
            instruction='From B1, go south and follow the southwest bend to Gate B2. Open B2; the click advances the guide.',
            warning='Confirm the target says Gate #B2 before interacting.',
        },
        {
            id='b_gate_3', area='B2 TO B3',
            path={'kb_b2_return','kb_b3_north','kb_b3_turn','gate_b3'},
            completion={kind='target_interaction',landmark='gate_b3',auto=true},
            instruction='Backtrack northeast from B2, return to the north hall, then turn west and north to Gate B3. Open B3.',
            warning='B3 is third even though the route passes near it earlier.',
        },
        {
            id='b_gate_4', area='B3 TO B4',
            path={'kb_b3_exit','kb_b4_west','kb_b4_south',
                'kb_b4_diagonal','gate_b4'},
            completion={kind='target_interaction',landmark='gate_b4',auto=true},
            instruction='Backtrack south from B3, take the west hall, then bend southwest to Gate B4 beside Device B. Open B4.',
            warning='If combat or geometry forces a different line, improvise freely and use //exg wp as needed.',
        },
        {
            id='b_gate_5', area='B4 TO B5',
            path={'kb_b4_exit','kb_b5_north','gate_b5'},
            completion={kind='target_interaction',landmark='gate_b5',auto=true},
            instruction='From B4, go west around the bend and south to Gate B5. Open B5.',
            warning='Confirm Gate #B5 before interacting.',
        },
        {
            id='b_gate_6', area='B5 TO B6',
            path={'kb_b5_east','kb_b6_north','kb_b6_west','gate_b6'},
            completion={kind='target_interaction',landmark='gate_b6',auto=true},
            instruction='From B5, go east, take the north jog, then turn west and north to Gate B6. Open B6.',
            warning='B6 must be last. The guide advances on Dolo\'s actual B6 interaction.',
        },
        {
            id='b_key_chest', area='KEY B', waypoint='gate_b6',
            objective='key_b', reward={scope='ground_floor',label='Key B chest'},
            completion={kind='all_temp_item', item='key_b', auto=true},
            instruction='Open the Key B chest that appears after B6, then wait briefly for all-six Key B evidence.',
            warning='If no chest appears, the order was broken. Do not idle: //exg next and salvage any other objective.',
        },
        {
            id='move_to_d_entry', area='B TO D',
            path={'kb_device_west','kb_device_entry','device_b','device_c',
                'kd_c_west','kd_entry'},
            completion={kind='landmark',landmark='kd_entry',auto=true},
            instruction='Return to Device B, teleport manually to Device C, then take the west passage through the D entrance at H-9. Stop at the first six-job party.',
            warning='This starts the optional Demisang sweep. Choose another objective at any time; nothing is locked or gated.',
            detail={'A teleport jump automatically catches the arrow up from Device B to Device C.'},
        },
        {
            id='d_opening_party', area='D ROOM 1', waypoint='d_entry_party',
            profile='sortie_objective_d_demisang_clear_v1',
            completion={kind='manual'},
            instruction='Run //exg profile once to load the Demisang combat setup inert. Clear the six regular Demisang in the entrance room. If convenient, kill WAR > MNK > WHM > BLM > RDM > THF for both blue-casket bonuses, then //exg next.',
            warning='That order is only for bonus caskets. Survival and improvisation win; Sheet D only cares that every regular Demisang eventually dies.',
            detail={
                'Position manually, let Tackle engage first when practical, select the intended target on Dolo, then press Ctrl-P or use //pt force.',
                'Alt-P stops combat immediately. Manual movement, targeting, spells, abilities, and retargeting always remain available.',
            },
        },
        {
            id='d_boss_side_rooms', area='D ROOMS 2-5',
            path={'d_south_hall','d_upper_boss','d_east_boss',
                'd_lower_boss','d_southwest_entry'},
            profile='sortie_objective_d_demisang_clear_v1',
            completion={kind='manual'},
            instruction='Work south room by room: clear the hallway, upper plaza, east branch, and lower boss-side plaza. Reach the southwest passage only after checking both sides, then //exg next.',
            warning='Kill regular Demisang only. Demisang Deleterious is optional and is never part of the Sheet D clear.',
        },
        {
            id='d_southwest_rooms', area='D ROOMS 6-10',
            path={'d_southwest_gate','d_southwest_center',
                'd_southwest_west','d_southwest_north'},
            profile='sortie_objective_d_demisang_clear_v1',
            completion={kind='manual'},
            instruction='Sweep the southwest side completely: Gate D1 side, center plaza, far-west branch, then north branch. Visually check every room before //exg next.',
            warning='The last two room centers are provisional. Follow the real corridor, use //exg wp if an arrow point is wrong, and keep clearing.',
        },
        {
            id='d_square_loop', area='D ROOMS 11-13',
            path={'d_ring_west','d_ring_north','d_ring_east'},
            profile='sortie_objective_d_demisang_clear_v1',
            completion={kind='manual'},
            instruction='Clear the square-loop corridor clockwise: west side, north side and room, then east side and branch. Finish any links before //exg next.',
            warning='Walking over a waypoint only moves the arrow; it never claims the room is clear. You decide when to advance the step.',
        },
        {
            id='d_d2_rooms', area='D ROOMS 14-15',
            path={'d_d2_south','d_d2_west','gate_d2'},
            profile='sortie_objective_d_demisang_clear_v1',
            completion={kind='manual'},
            instruction='Clear the room south of D2 and the entire west plaza, then return to Gate D2. Open it if needed and use //exg next.',
            warning='Check corners before leaving; the addon cannot count living Demisang.',
        },
        {
            id='d_device_rooms', area='D ROOMS 16-17',
            path={'d_device_nw','d_device_north','d_device_return'},
            profile='sortie_objective_d_demisang_clear_v1',
            completion={kind='manual'},
            instruction='Finish the Device D side: clear the northwest small room and the full north plaza, then return to Device D. Revisit any skipped branch before //exg next.',
            warning='These final two points are provisional next-run calibration. If geometry disagrees, follow the actual halls and skip arrow points without hesitation.',
            detail={'Sheet D requires every regular Demisang. There is no required overall kill order and Deleterious does not count.'},
        },
        {
            id='sheet_d', area='BITZER D', waypoint='bitzer_d',
            objective='sheet_d', reward={scope='ground_floor',label='Sheet D chest'},
            completion={kind='all_temp_item', item='sheet_d', auto=true},
            instruction='After the full visual room audit, touch Bitzer D and open the Sheet D chest. Wait briefly for all-six Sheet D evidence.',
            warning='No chest means something remains alive. Use //exg back to resume the sweep, or stop and salvage/exit; the addon never traps the run.',
        },
        {
            id='complete', area='FINISH',
            completion={kind='all_temp_items', auto=true, items={'key_b','sheet_d'}},
            instruction='Key B and Sheet D are confirmed on all six. Spend the remaining time however you choose, then exit normally.',
            warning='The guide is complete; it imposes no restriction on the rest of the run.',
        },
    },
}
