-- The evolving production route for this six-character party. Navigation is
-- point-to-point. One persistent PartyTactics profile is loaded after entry;
-- exact hostile targets select recipes inside it without profile transitions.

local function point(name, x, y, z, cue, radius, confidence)
    return {
        name=name, x=x, y=y, z=z,
        radius=radius or 12, z_tolerance=40,
        cue=cue,
        coordinate_semantics='public_map_corridor_trace',
        confidence=confidence or 'provisional_map_trace',
    }
end

local function facts(objective, why, success, automation, next_step)
    return {
        'OBJECTIVE: '..objective,
        'WHY: '..why,
        'SUCCESS: '..success,
        'AUTOMATION: '..automation,
        'NEXT: '..next_step,
    }
end

local route = {
    schema=1,
    id='sortie-main-run',
    aliases={'run','mainrun','therun'},
    version='1.2.0',
    title='Sortie: evolving main run (C > Skomora > B > Leshonn > A > Ghatjot)',
    content='sortie',
    allowed_zones={
        [133]=true, [189]=true, [275]=true,
        [267]=true, [281]=true,
    },
    guide_only=false,
    auto_start=true,
    target_selected_combat=false,

    landmarks={
        -- C: avoid the Corse room by Device C. The preferred Skeleton/Ghoul
        -- pack is outside Gadget C and naturally lies on the Skomora route.
        c_device_south=point('C: south hall from Device C',
            -460, -220, -162, 'Leave Device C south and follow the hall.'),
        c_gate3_west=point('C: west approach to Gate C3',
            -400, -260, -166, 'Continue southeast toward Gate C3.'),
        c_gate3_exit=point('C: south turn after Gate C3',
            -340, -340, -176, 'Through C3, follow the corridor south.'),
        c_gate2_west=point('C: west approach to Gate C2',
            -250, -340, -180, 'Turn east, then southeast to Gate C2.'),
        c_bottom_east=point('C: long lower east hall',
            -80, -403, -190, 'Follow the lower corridor east.'),
        c_gate1_south=point('C: south of Gate C1',
            -60, -405, -194, 'After checking C1, backtrack south.'),
        c_safe_camp=point('C: Skeleton/Ghoul camp near Gadget C',
            -60, -390, -194,
            'Use only Cachaemic Skeletons and Ghouls here; ignore Corses and the Bhoot.',
            18, 'operator_selected_provisional'),
        c_gadget_bend=point('C: final bend to Gadget C',
            -25, -425, -198, 'Take the short southeast branch.'),

        -- B: the public guide places Fire Elementals in the large room north
        -- of Bitzer B. These points remain deliberately easy to live-calibrate.
        b_bitzer_west=point('B: west side of Device B room',
            -405, -20, -154, 'Leave Device B toward Bitzer B.'),
        b_fire_south=point('B: south approach to Fire room',
            -405, 100, -170, 'Take the north corridor toward the large room.'),
        b_fire_camp=point('B: Fire Elemental room north of Bitzer B',
            -405, 220, -182,
            'Engage Biune Fire Elementals; the full party earns one qualifying WS per target.',
            22, 'public_guide_provisional'),
        b_fire_east=point('B: east exit from Fire room',
            -300, 220, -182, 'Leave the Fire room east.'),
        b_upper_east=point('B: upper east corridor',
            -180, 220, -180, 'Continue east toward Gate B3.'),
        b_gate3_exit=point('B: north branch after Gate B3',
            -80, 260, -184, 'Through B3, take the north branch.'),
        b_gadget_south=point('B: south approach to Gadget B',
            -60, 360, -194, 'Continue north, then turn east into Gadget B.'),

        -- A: this is the user's chosen northwestern Acuex pack next to the
        -- efficient Ghatjot line, not a geographically interchangeable pack.
        a_device_east=point('A: east exit from Device A',
            -420, 96, -152, 'Leave Device A east, then turn north.'),
        a_east_north=point('A: long eastern north hall',
            -420, 285, -174, 'Continue north to the angled bend.'),
        a_east_bend=point('A: northeast bend',
            -460, 325, -182, 'Follow the bend north, then west.'),
        a_top_east=point('A: upper east corridor',
            -460, 380, -190, 'Turn west across the upper corridor.'),
        a_gate3_west=point('A: west of Gate A3',
            -520, 390, -194, 'Open A3 if closed and continue west.'),
        a_mid_north=point('A: upper middle turn',
            -580, 390, -194, 'Turn south around the center room.'),
        a_mid_south=point('A: lower middle turn',
            -580, 340, -188, 'Turn west through the next passage.'),
        a_gate2_east=point('A: east of Gate A2',
            -700, 340, -188, 'Open A2 if closed, then turn north.'),
        a_acuex_camp=point('A: northwest Acuex camp near Gadget A',
            -700, 390, -196,
            'Use the Abject Acuex on this Ghatjot-side route.',
            20, 'operator_selected_provisional'),
        a_upper_west=point('A: upper west corridor',
            -820, 390, -198, 'Continue west toward the northwest bend.'),
        a_gadget_bend=point('A: final bend to Gadget A',
            -860, 420, -200, 'Take the short northwest branch.'),
    },

    run_transactions={
        {id='c_shard_access',rewind='travel_c_camp',
            goal={kind='all_temp_item',item='shard_c'}},
        {id='c_metal_safety',rewind='c_shard',
            goal={kind='all_temp_item',item='metal_c'}},
        {id='skomora_clear',rewind='stage_skomora',
            goal={kind='all_temp_item',item='shard_g'}},
        {id='b_shard_access',rewind='travel_b_camp',
            goal={kind='all_temp_item',item='shard_b'}},
        {id='leshonn_clear',rewind='stage_leshonn',
            goal={kind='all_temp_item',item='shard_f'}},
        {id='a_shard_access',rewind='travel_a_camp',
            goal={kind='all_temp_item',item='shard_a'}},
        {id='a_metal_safety',rewind='a_shard',
            goal={kind='all_temp_item',item='metal_a'}},
        {id='ghatjot_clear',rewind='stage_ghatjot',
            goal={kind='all_temp_item',item='shard_e'}},
    },

    steps={
        {
            id='preentry', area='OUTSIDE: READY',
            completion={kind='all_key_item',item='shiny_plate',auto=true},
            instruction='Gather all six at the Kamihr transposer with a Shiny plate, food, Reraise, and inventory space.',
            warning='Entry itself is the one external confirmation ExpeditionGuide cannot safely issue. Nothing else in this route requires a profile or combat command.',
            detail=facts(
                'Prepare the established COR/DNC, PLD/SCH, DNC/WAR, BRD/WHM, RDM/WHM, GEO/WHM party.',
                'The run is timed; food, Reraise, medicines, and free inventory prevent avoidable stops.',
                'All six report a Shiny Ra\'Kaznarian plate.',
                'The guide is already started. One persistent Sortie profile loads once after entry and stays armed.',
                'Dolo confirms entry at the transposer; the guide binds the new run automatically.'),
        },
        {
            id='enter', area='ENTRY: LOAD IN',
            completion={kind='all_in_pack',auto=true},
            instruction='Enter Sortie and let all six finish zoning; movement begins as soon as the six-client run is bound.',
            warning='Do not wait for a manual “next.” Fresh reports advance this step automatically.',
            detail=facts(
                'Get the complete party inside the same Sortie instance.',
                'The route will not trust rewards or issue a party warp until all six belong to this run.',
                'The HUD reports six of six inside and advances to Device C.',
                'Run identity, timer, and party evidence bind without a command.',
                'The starting Device sends the party directly to C.'),
        },
        {
            id='warp_c', area='C: DEVICE WARP',
            path={'device_start','device_c'},
            automation={kind='sortie_superwarp',operation='device_c'},
            completion={kind='landmark',landmark='device_c',auto=true},
            instruction='Stand near the starting Device; the party warp to Device C fires automatically.',
            warning='The request waits until the starting Device is actually in range. If the warp fails, it retries every 12 seconds while this step remains current.',
            detail=facts(
                'Move all six from the entrance to Device C.',
                'C first preserves Umbra\'s boss order and puts the efficient Skeleton/Ghoul pack on the Skomora line.',
                'Dolo arrives at Device C and the route advances.',
                'ExpeditionGuide detects the nearby Device, requests C, and retries until relocation succeeds.',
                'Use the HUD route cues through C3, C2, and C1; the calibration arrow is optional and currently disabled.'),
        },
        {
            id='travel_c_camp', area='C: SAFE BURST CAMP',
            path={'c_device_south','c_gate3_west','gate_c3','c_gate3_exit',
                'c_gate2_west','gate_c2','c_bottom_east','gate_c1',
                'c_gate1_south','c_safe_camp'},
            completion={kind='landmark',landmark='c_safe_camp',auto=true},
            instruction='From Device C, go through C3, C2, and C1 to the Skeleton/Ghoul pack just outside Gadget C; open encountered gates and ignore the Corse room.',
            warning='This camp choice is intentional: Cachaemic Corses are slower and more dangerous. Never pull the Cachaemic Bhoot for burst credit.',
            detail=facts(
                'Reach normal Cachaemic Skeletons or Ghouls near Skomora.',
                'They are safer than Corses and eliminate a wasteful out-and-back trip.',
                'Dolo reaches the marked camp beside the Gadget-C branch.',
                'The persistent profile stays in movement mode until an exact Skeleton or Ghoul selects its internal C recipe.',
                'Burst three targets for Shard C, then three more for Metal C.'),
        },
        {
            id='c_shard', area='C: SHARD 0/3', waypoint='c_safe_camp',
            objective='shard_c_burst',
            reward={scope='ground_floor',label='Shard C chest'},
            completion={kind='all_temp_item',item='shard_c',auto=true},
            instruction='Have Tackle engage one Skeleton or Ghoul at a time; the party automatically chains, bursts, finishes, and repeats until Shard C appears.',
            warning='No profile command and no force command is expected. Any party member may improvise; the automation never filters manual actions.',
            detail=facts(
                'Land a Magic Burst on each of three Cachaemic Skeletons/Ghouls before it dies.',
                'Shard C opens Skomora. Exact easy targets protect time and MP.',
                'Open the chest; all six report Shard C.',
                'The C recipe takes over inside the loaded profile: Tackle pulls; Kick > Dolo makes Fragmentation; Smalls and Achoo burst Thunder; all six finish.',
                'Stay in the same camp for three additional credits.'),
        },
        {
            id='c_metal', area='C: METAL 3/6', waypoint='c_safe_camp',
            objective='metal_c_burst',
            reward={scope='ground_floor',label='Metal C chest'},
            completion={kind='all_temp_item',item='metal_c',auto=true},
            instruction='Repeat the automatic burst sequence on three more Skeletons/Ghouls, then open the Metal C chest with all six present.',
            warning='Metal C is retained in this proof route because it makes Skomora recovery materially safer; it can be optimized out only after repeatable wins.',
            detail=facts(
                'Earn three more qualifying Magic Bursts after Shard C.',
                'Metal C converts Skomora\'s Haunted effect into removable Curse.',
                'Open the chest; all six report Metal C.',
                'The profile stays armed across exact targets and retries a failed chain instead of idling at 3000 TP.',
                'Take the nearby branch to Gadget C.'),
        },
        {
            id='travel_gadget_c', area='C: GADGET',
            path={'c_safe_camp','c_gadget_bend','gadget_c'},
            completion={kind='landmark',landmark='gadget_c',auto=true},
            instruction='Take the short branch from the Skeleton/Ghoul camp into Gadget C.',
            detail=facts(
                'Gather all six at Diaphanous Gadget C.',
                'Shard C is ready and Skomora is the next boss.',
                'Dolo reaches the Gadget-C interaction radius.',
                'The same Sortie profile remains loaded; target retirement switches support back to movement mode.',
                'The Gadget ports the party into Skomora automatically.'),
        },
        {
            id='stage_skomora', area='C: ENTER SKOMORA', waypoint='gadget_c',
            automation={kind='sortie_superwarp',operation='port'},
            completion={kind='relocation',auto=true},
            instruction='Remain beside Gadget C; ExpeditionGuide detects it and keeps retrying the party port until arena relocation is confirmed.',
            warning='After arrival, Tackle engages first. Dolo and every attacker close distance automatically; no arm/force command is part of the workflow.',
            detail=facts(
                'Move the complete party into the Skomora arena.',
                'The Metal-C-safe boss proof produces Shard G and gallimaufry.',
                'A large relocation into the arena is observed before the HUD advances to the boss.',
                'The nearby Gadget is detected and the port retries until arrival; Skomora selects an internal recipe without loading another profile.',
                'Stack in melee range and let Tackle establish initial threat.'),
        },
        {
            id='skomora', area='BOSS C: SKOMORA',
            objective='boss_skomora',
            reward={scope='ground_floor',label='Skomora reward chest'},
            completion={kind='all_temp_item',item='shard_g',auto=true},
            instruction='Tackle engages Skomora; all six close, fight, maintain the lean buff package, and recover automatically. Open the reward chest after the kill.',
            warning='Stay stacked for Setting the Stage. Haunted becomes removable Curse with Metal C. Skomora absorbs Dark damage.',
            detail=facts(
                'Defeat Skomora and collect the full-party reward.',
                'This is boss one, Shard G, and the first damage benchmark.',
                'All six report Shard G after the chest opens.',
                'Tackle gets the opening threat window; the other five release without a leader gate and spend TP promptly.',
                'The arena Gadget returns the party to C automatically.'),
        },
        {
            id='exit_skomora', area='C: EXIT BOSS', waypoint='gadget_c',
            path={'gadget_c'},
            automation={kind='sortie_superwarp',operation='port'},
            completion={kind='relocation',auto=true},
            instruction='Stand by the arena Gadget; the party returns to exterior Gadget C automatically.',
            detail=facts(
                'Leave the Skomora arena.',
                'The next target is B without retracing on foot inside the arena.',
                'Dolo appears beside exterior Gadget C.',
                'The nearby arena Gadget is detected; the return port retries until relocation is confirmed.',
                'Return through C1, C2, and C3 to Device C.'),
        },
        {
            id='return_device_c', area='C: RETURN DEVICE',
            path={'c_gadget_bend','c_gate1_south','gate_c1','c_bottom_east',
                'gate_c2','c_gate2_west','c_gate3_exit','gate_c3',
                'c_gate3_west','c_device_south','device_c'},
            completion={kind='landmark',landmark='device_c',auto=true},
            instruction='Backtrack through C1, C2, and C3 to Device C; use the HUD route cues at each turn.',
            detail=facts(
                'Return to Device C.',
                'The Device is the fastest transfer from completed C to B.',
                'Dolo reaches Device C.',
                'Navigation catches up if you cut a corner; no combat policy is tied to the corridor.',
                'The party warps to Device B automatically.'),
        },
        {
            id='warp_b', area='B: DEVICE WARP',
            path={'device_c','device_b'},
            automation={kind='sortie_superwarp',operation='device_b'},
            completion={kind='landmark',landmark='device_b',auto=true},
            instruction='Stand near Device C; the party warp to Device B fires automatically.',
            detail=facts(
                'Transfer all six to Sector B.',
                'Five nearby Biune Fire Elementals earn access to Leshonn.',
                'Dolo arrives at Device B.',
                'ExpeditionGuide detects Device C, requests B, and retries until relocation succeeds.',
                'From Device B, pass Bitzer B and take the north corridor into the Fire room.'),
        },
        {
            id='travel_b_camp', area='B: FIRE ROOM',
            path={'b_bitzer_west','b_fire_south','b_fire_camp'},
            completion={kind='landmark',landmark='b_fire_camp',auto=true},
            instruction='From Bitzer B, take the north corridor into the large Fire room. Pull and kill five Biune Fire Elementals; land at least one weapon skill on every target before it dies.',
            warning='The B corridor trace is new and intentionally provisional. The objective is the large Fire room north of Bitzer B; the real hallway wins over a bad waypoint cue.',
            detail=facts(
                'Reach the five-target Fire Elemental camp.',
                'This pack sits on the efficient Leshonn line and supports fast TP gain.',
                'Dolo reaches the marked camp in the large room north of Bitzer B.',
                'An exact Biune elemental selects the B recipe inside the already-loaded Sortie profile.',
                'Tackle begins the first full-party burn.'),
        },
        {
            id='b_shard', area='B: SHARD 0/5', waypoint='b_fire_camp',
            objective='shard_b_weapon_skill',
            reward={scope='ground_floor',label='Shard B chest'},
            completion={kind='all_temp_item',item='shard_b',auto=true},
            instruction='Have Tackle pull five Biune Fire Elementals in succession. All six close and attack; ready characters weapon-skill promptly so each target receives qualifying WS damage before death.',
            warning='Metal B would require five additional elementals. This route stops at Shard B for speed; the first Leshonn proof will tell us whether the extra safety repays its cost.',
            detail=facts(
                'Perform at least one weapon skill on each of five Biune foes before killing it.',
                'Five credits produce Shard B, which opens Leshonn.',
                'Open the chest; all six report Shard B.',
                'Any party claim starts the same fast burn. The runtime spends ready TP continuously and never disengages or pauses the party for this objective.',
                'Continue east through B3 to Gadget B.'),
        },
        {
            id='travel_gadget_b', area='B: GADGET',
            path={'b_fire_east','b_upper_east','gate_b3','b_gate3_exit',
                'b_gadget_south','gadget_b'},
            completion={kind='landmark',landmark='gadget_b',auto=true},
            instruction='Leave the Fire room east, pass through Gate B3, then turn north and east into Gadget B; use the HUD route cues at each junction.',
            detail=facts(
                'Gather all six at Diaphanous Gadget B.',
                'Shard B is ready; Leshonn is boss two.',
                'Dolo reaches Gadget B.',
                'The persistent profile returns to movement support; Leshonn will select his internal boss recipe.',
                'The Gadget ports the party into Leshonn automatically.'),
        },
        {
            id='stage_leshonn', area='B: ENTER LESHONN', waypoint='gadget_b',
            automation={kind='sortie_superwarp',operation='port'},
            completion={kind='relocation',auto=true},
            instruction='Remain beside Gadget B; ExpeditionGuide detects it and keeps retrying the party port until arena relocation is confirmed.',
            warning='Metal B is intentionally absent. Expect basic-attack Stun in thunder hands or Weight in wind hands; neither condition blocks manual play.',
            detail=facts(
                'Move all six into the Leshonn arena.',
                'This is the new third-segment proof and yields Shard F plus boss gallimaufry.',
                'A large relocation into the arena advances the HUD.',
                'The nearby Gadget is detected and the port retries until arrival; Leshonn changes only the internal recipe.',
                'Before the pull, put Tackle alone in front; place the other five behind or on a rear flank.'),
        },
        {
            id='leshonn', area='BOSS B: LESHONN',
            objective='boss_leshonn',
            reward={scope='ground_floor',label='Leshonn reward chest'},
            completion={kind='all_temp_item',item='shard_f',auto=true},
            instruction='Select Leshonn on Dolo to stage the safe boss mode. Put Tackle alone directly in front; put Dolo, Kick, Barney, Smalls, and Achoo behind or on a rear flank. Then engage with Tackle and open the reward chest after the kill.',
            warning='Use no Dia, Elegy, Flash, Sentinel, or other routine debuff. Automation keeps only GEO bubbles and Box Step, and Kick holds WS. Lightning hands copy enfeebles and can stun-lock; wind hands steal buffs. Never use Wind or Lightning damage.',
            detail=facts(
                'Defeat Leshonn with Tackle as the only character in front, then collect the reward.',
                'Front counters can exceed 500 damage; matching Wind/Lightning damage heals the boss; Lightning copies debuffs and Wind steals buffs.',
                'All six report Shard F and the reward chest is opened.',
                'Targeting Leshonn stages zero-debuff BRD/RDM support and disables automated PLD Flash/Sentinel without engaging. Tackle starts combat; Dolo/Tackle/Barney use Savage Blade, Smalls/Achoo use Black Halo, Kick melees and uses Box Step but holds WS. Positioning is never an automation gate.',
                'The arena Gadget returns the party to B automatically.'),
        },
        {
            id='exit_leshonn', area='B: EXIT BOSS', waypoint='gadget_b',
            path={'gadget_b'},
            automation={kind='sortie_superwarp',operation='port'},
            completion={kind='relocation',auto=true},
            instruction='Stand by the arena Gadget; the party returns to exterior Gadget B automatically.',
            detail=facts(
                'Leave the Leshonn arena.',
                'A and Ghatjot are next.',
                'Dolo appears beside exterior Gadget B.',
                'The nearby arena Gadget is detected; the return port retries until relocation is confirmed.',
                'Return west and south through Gate B3 and the Fire room to Device B.'),
        },
        {
            id='return_device_b', area='B: RETURN DEVICE',
            path={'b_gadget_south','b_gate3_exit','gate_b3','b_upper_east',
                'b_fire_east','b_fire_camp','b_fire_south','b_bitzer_west',
                'device_b'},
            completion={kind='landmark',landmark='device_b',auto=true},
            instruction='Backtrack through Gate B3 and the Fire room to Device B; use the HUD route cues at each junction.',
            detail=facts(
                'Return to Device B.',
                'The Device is the fastest transfer from B to the Acuex/Ghatjot line.',
                'Dolo reaches Device B.',
                'The route path remains loaded through temporary sensor gaps.',
                'The party warps to Device A automatically.'),
        },
        {
            id='warp_a', area='A: DEVICE WARP',
            path={'device_b','device_a'},
            automation={kind='sortie_superwarp',operation='device_a'},
            completion={kind='landmark',landmark='device_a',auto=true},
            instruction='Stand near Device B; the party warp to Device A fires automatically.',
            detail=facts(
                'Transfer all six to Sector A.',
                'Six Acuex credits provide Shard/Metal A immediately before Ghatjot.',
                'Dolo arrives at Device A.',
                'ExpeditionGuide detects Device B, requests A, and retries until relocation succeeds.',
                'Follow the HUD route cues to the northwest Acuex camp beside the Ghatjot route.'),
        },
        {
            id='travel_a_camp', area='A: ACUEX CAMP',
            path={'a_device_east','a_east_north','a_east_bend','a_top_east',
                'a_gate3_west','a_mid_north','a_mid_south','a_gate2_east',
                'a_acuex_camp'},
            completion={kind='landmark',landmark='a_acuex_camp',auto=true},
            instruction='From Device A, follow the east corridor around to the northwest Abject Acuex camp beside the Ghatjot route; use the HUD cues at each turn.',
            warning='This location is fixed by operational efficiency, not “any Acuex”: use the northwest pack near Gadget A.',
            detail=facts(
                'Reach the selected Acuex pack near Ghatjot.',
                'It avoids the earlier detour and places the party beside its next boss.',
                'Dolo reaches the marked northwest camp.',
                'An exact Acuex switches the persistent profile to its Liquefaction/Fire recipe automatically.',
                'Tackle starts the first full-party TP burn.'),
        },
        {
            id='a_shard', area='A: SHARD 0/3', waypoint='a_acuex_camp',
            objective='shard_a_magic',
            reward={scope='ground_floor',label='Shard A chest'},
            completion={kind='all_temp_item',item='shard_a',auto=true},
            instruction='Have Tackle engage three Acuex in succession; the party burns for TP, then automatically executes Liquefaction and a protected Fire burst for each magic kill.',
            warning='Do not issue force, arm, or profile commands. Aquaveil is maintained so Smalls is not slapped out of the burst; failed chains rebuild and retry automatically.',
            detail=facts(
                'Kill three Abject Acuex with single-target magic as the killing blow.',
                'Shard A opens Ghatjot.',
                'Open the chest; all six report Shard A.',
                'All six build TP; Tackle Flat Blade > Smalls Red Lotus Blade makes Liquefaction; Smalls queues Fire IV then Fire III inside the burst window.',
                'Stay here for three more identical credits.'),
        },
        {
            id='a_metal', area='A: METAL 3/6', waypoint='a_acuex_camp',
            objective='metal_a_magic',
            reward={scope='ground_floor',label='Metal A chest'},
            completion={kind='all_temp_item',item='metal_a',auto=true},
            instruction='Repeat the automatic Liquefaction and Fire finish on three more Acuex, then open the Metal A chest.',
            warning='The full party keeps damage fast; the runtime—not the operator—stops physical damage for the chain and final nuke.',
            detail=facts(
                'Earn three more single-target magic killing blows after Shard A.',
                'Metal A turns Ghatjot\'s Taint into removable Poison.',
                'Open the chest; all six report Metal A.',
                'Smalls uses a lean buff set, Aquaveil, Refresh support, and automatic Convert thresholding to protect MP.',
                'Continue west to Gadget A.'),
        },
        {
            id='travel_gadget_a', area='A: GADGET',
            path={'a_acuex_camp','a_upper_west','a_gadget_bend','gadget_a'},
            completion={kind='landmark',landmark='gadget_a',auto=true},
            instruction='Leave the Acuex camp west, round the northwest bend, and enter Gadget A.',
            detail=facts(
                'Gather all six at Diaphanous Gadget A.',
                'Shard/Metal A are ready and Ghatjot is boss three.',
                'Dolo reaches Gadget A.',
                'Combat changes only when exact Ghatjot is engaged.',
                'The Gadget ports the party into Ghatjot automatically.'),
        },
        {
            id='stage_ghatjot', area='A: ENTER GHATJOT', waypoint='gadget_a',
            automation={kind='sortie_superwarp',operation='port'},
            completion={kind='relocation',auto=true},
            instruction='Remain beside Gadget A; ExpeditionGuide detects it and keeps retrying the party port until arena relocation is confirmed.',
            warning='After arrival, Tackle engages first. No Water damage, Water Shot, Leaden Salute, Distortion, or Darkness.',
            detail=facts(
                'Move all six into the Ghatjot arena.',
                'Metal A makes Taint recoverable and the third boss completes this proof route.',
                'A large relocation into the arena advances the HUD.',
                'The nearby Gadget is detected and the port retries until arrival; Ghatjot changes only the internal recipe.',
                'Stack in melee, put Tackle in front, and engage.'),
        },
        {
            id='ghatjot', area='BOSS A: GHATJOT',
            objective='boss_ghatjot',
            reward={scope='ground_floor',label='Ghatjot reward chest'},
            completion={kind='all_temp_item',item='shard_e',auto=true},
            instruction='Tackle engages Ghatjot; all six close and execute the no-Water plan. Remove Poison immediately and open the reward chest after the kill.',
            warning='Absolutely no Water-aligned damage or Distortion/Darkness. Tackle gets initial threat; poison recovery has priority over marginal offense.',
            detail=facts(
                'Defeat Ghatjot and collect the full-party reward.',
                'Boss three establishes the next baseline for extending THE run.',
                'All six report Shard E.',
                'Savage Blade, Evisceration, and Black Halo provide known usable offense without the forbidden Water result; support persists instead of full rebuffing each transition.',
                'The proof route completes; remaining time is free for salvage and the next expansion.'),
        },
        {
            id='complete', area='THREE BOSSES COMPLETE',
            completion={kind='all_temp_items',auto=true,
                items={'shard_g','shard_f','shard_e'}},
            instruction='Skomora, Leshonn, and Ghatjot are complete. Use remaining time freely; the next development segment will extend this route rather than replace it.',
            warning='The guide is finished, not the expedition. It never blocks bonus objectives, salvage, exploration, or an improvised exit.',
            detail=facts(
                'Confirm the C > B > A three-boss foundation.',
                'This is the reusable spine for the eventual nine-boss route.',
                'Shard G, Shard F, and Shard E are present on all six.',
                'Encounter requests retire after each target; the one Sortie profile remains armed and returns support to movement mode.',
                'Review timing, navigation calibration, MP, deaths, and damage from the full run before adding the next boss.'),
        },
    },
}

-- Load and arm exactly one combat owner after the party is inside. Keeping the
-- same desired state on every later step makes ProfileBridge emit once; route
-- advancement can never stop, reload, or replace combat between objectives.
for index,step in ipairs(route.steps) do
    if index>=3 then
        step.profile='sortie_main_v1'
        step.profile_arm=true
    end
end

return route
