-- First repeatable two-boss training route for this exact party. It preserves
-- Umbra's C-before-A order while deliberately earning both Metals. Profile
-- transitions and supported Device/Gadget operations are automatic; movement,
-- target selection, and every manual override remain operator-owned. Public-map
-- waypoints are turn-by-turn provisional anchors and remain skippable.

local function point(name, x, y, z, cue, radius)
    return {
        name=name, x=x, y=y, z=z,
        radius=radius or 12, z_tolerance=40,
        cue=cue,
        coordinate_semantics='public_map_corridor_trace',
        confidence='provisional_map_trace',
    }
end

return {
    schema=1,
    id='sortie-two-boss-c-a-training',
    aliases={'boss2','twoboss','ca'},
    version='2.1.0',
    title='Sortie: Skomora + Ghatjot training',
    content='sortie',
    allowed_zones={
        [133]=true, [189]=true, [275]=true,
        [267]=true, [281]=true,
    },
    guide_only=false,

    landmarks={
        c_objective_room=point('C burst camp by Device C',
            -410, -175, -158,
            'Enter the nearby Cachaemic room and pull one foe at a time.'),
        c_device_south_turn=point('C route: southeast bend',
            -410, -235, -166,
            'Follow the corridor south, then turn east.'),
        c_gate3_west=point('C route: west of Gate C3',
            -355, -245, -168,
            'Continue east to Gate C3.'),
        c_gate3_south=point('C route: south of Gate C3',
            -340, -340, -176,
            'After C3, take the corridor south.'),
        c_gate2_west=point('C route: west approach to Gate C2',
            -250, -340, -180,
            'Turn east, then southeast toward Gate C2.'),
        c_bottom_east=point('C route: long east hall',
            -80, -403, -190,
            'Follow the bottom corridor east, then turn north.'),
        c_gadget_south=point('C route: south from Gate C1',
            -60, -405, -194,
            'Backtrack south from C1 and take the southeast boss branch.'),
        c_gadget_east=point('C route: Gadget C final bend',
            -25, -425, -198,
            'Turn toward the southeast Gadget room.'),

        a_device_east=point('A route: east exit from Device A',
            -420, 96, -152,
            'Leave Device A to the east, then turn north.'),
        a_east_north=point('A route: long north hall',
            -420, 285, -174,
            'Continue north to the angled west bend.'),
        a_east_bend=point('A route: northeast bend',
            -460, 325, -182,
            'Follow the bend north, then west.'),
        a_top_east=point('A route: upper east hall',
            -460, 380, -190,
            'Turn west across the upper corridor.'),
        a_gate3_west=point('A route: west of Gate A3',
            -520, 390, -194,
            'Open A3 if needed and continue west.'),
        a_mid_north=point('A route: upper middle turn',
            -580, 390, -194,
            'Turn south briefly around the central room.'),
        a_mid_south=point('A route: lower middle turn',
            -580, 340, -188,
            'Turn west through the next passage.'),
        a_gate2_east=point('A route: east of Gate A2',
            -700, 340, -188,
            'Open A2 if needed, then turn north.'),
        a_objective_camp=point('A magic-kill camp',
            -700, 390, -196,
            'Use the nearby Abject packs for single-target magic killing blows.'),
        a_upper_west=point('A route: upper west corridor',
            -820, 390, -198,
            'Continue west, then follow the northwest bend.'),
        a_gadget_bend=point('A route: Gadget A bend',
            -860, 420, -200,
            'Take the short northwest branch into the Gadget room.'),
    },

    run_transactions={
        {id='c_shard_access', rewind='c_objective_setup',
            goal={kind='all_temp_item', item='shard_c'}},
        {id='c_metal_safety', rewind='c_shard',
            goal={kind='all_temp_item', item='metal_c'}},
        {id='skomora_clear', rewind='skomora_stage',
            goal={kind='all_temp_item', item='shard_g'}},
        {id='a_shard_access', rewind='a_objective_setup',
            goal={kind='all_temp_item', item='shard_a'}},
        {id='a_metal_safety', rewind='a_shard',
            goal={kind='all_temp_item', item='metal_a'}},
        {id='ghatjot_clear', rewind='ghatjot_stage',
            goal={kind='all_temp_item', item='shard_e'}},
    },

    steps={
        {
            id='preentry', area='OUTSIDE',
            completion={kind='all_key_item',item='shiny_plate',auto=true},
            instruction='Get a Shiny Ra\'Kaznarian plate on all six, use food, and gather at the Kamihr transposer. Recommended first-proof subjobs: COR/DNC, PLD/WAR, DNC/WAR, BRD/WHM, RDM/WHM, GEO/WHM.',
            warning='All six main-job soul key items are already confirmed. Do not spend route time rechecking them. Subjob differences are advice, never a gate.',
            detail={
                'Bring Silent Oils, Prism Powders, Holy Water, Poison-removal supplies, Reraise, and inventory space.',
                'This route attempts Skomora C first, then Ghatjot A, and deliberately earns both Metals for training safety.',
                'No REMA or Prime weapon is assumed. The two profiles use only modes verified in the current six inventories and GearSwap files.',
            },
        },
        {
            id='enter', area='ENTRY',
            completion={kind='all_in_pack',auto=true},
            instruction='Dolo enters manually. Bring all six through and wait for every client to finish loading.',
            warning='ExpeditionGuide never enters, moves, targets, interacts, or starts combat for you.',
        },
        {
            id='warp_device_c', area='TO DEVICE C',
            path={'device_start','device_c'},
            automation={kind='sortie_superwarp',operation='device_c'},
            completion={kind='landmark',landmark='device_c',auto=true},
            instruction='Gather at the starting Device. ExpeditionGuide automatically requests //sw so p c and resumes the arrow at Device C.',
            warning='Superwarp validates the nearby Device and confirms the party. If it cannot act, use any manual route or warp you need; the guide never locks controls.',
        },
        {
            id='c_objective_setup', area='C ACCESS SETUP',
            path={'c_objective_room'},
            profile='sortie_objective_c_magic_burst_v1',
            profile_arm=true,
            completion={kind='landmark',landmark='c_objective_room',auto=true},
            instruction='Move to the nearby Cachaemic room. The guide automatically runs //pt use sortie-objective-c-magic-burst-v1 armed; select one normal Cachaemic at a time on Dolo. Tackle pulls first automatically.',
            warning='Never select the Cachaemic Bhoot. The profile sequences only its own actions and never blocks movement, targets, attacks, spells, abilities, items, or an improvised manual burst.',
            detail={
                'Automatic sequence: Tackle claim, Kick Evisceration, Dolo Savage Blade for packet-confirmed Fragmentation, then Achoo Thunder with Smalls as a bounded fallback.',
                'Only an observed Magic Burst releases Tackle, Barney, and the automatic finishing weapon skills. A manual valid chain step or party Magic Burst also counts.',
            },
        },
        {
            id='c_shard', area='C SHARD 0/3', waypoint='c_objective_room',
            profile='sortie_objective_c_magic_burst_v1',
            profile_arm=true,
            objective='shard_c_burst',
            reward={scope='ground_floor',label='Shard C chest'},
            completion={kind='all_temp_item',item='shard_c',auto=true},
            instruction='Select each of three normal Cachaemic foes on Dolo. Tackle is directed first; after his claim, the armed profile completes Evisceration > Savage Blade > Thunder and releases finishers. Dolo opens the Shard C chest.',
            warning='The profile remains armed between exact targets. Count chest credit, not spell attempts; Alt-P or any manual recovery remains available.',
        },
        {
            id='c_metal', area='C METAL 3/6', waypoint='c_objective_room',
            profile='sortie_objective_c_magic_burst_v1',
            profile_arm=true,
            objective='metal_c_burst',
            reward={scope='ground_floor',label='Metal C chest'},
            completion={kind='all_temp_item',item='metal_c',auto=true},
            instruction='Select three more normal Cachaemic foes on Dolo; no repeated arm command is needed. Dolo opens the Metal C chest and waits for all six.',
            warning='Metal C is intentionally required for training safety because it converts Haunted into removable Curse. You may //exg skip, stop the profile, or improvise at any time.',
        },
        {
            id='travel_gadget_c', area='TO GADGET C',
            profile='sortie_boss_skomora_v1',
            path={'c_device_south_turn','c_gate3_west','gate_c3',
                'c_gate3_south','c_gate2_west','gate_c2','c_bottom_east',
                'gate_c1','c_gadget_south','c_gadget_east','gadget_c'},
            completion={kind='landmark',landmark='gadget_c',auto=true},
            instruction='Follow the floating arrow point by point through C3, C2, and C1 to Diaphanous Gadget C. The guide loads //pt use sortie-boss-skomora-v1 unarmed so support settles while you move.',
            warning='These corridor centers come from the public map and need live calibration. The real corridor is authoritative: use //exg wp to advance a bad point or //exg mark to replace it.',
        },
        {
            id='skomora_stage', area='GADGET C', waypoint='gadget_c',
            profile='sortie_boss_skomora_v1',
            profile_arm=true,
            automation={kind='sortie_superwarp',operation='port'},
            completion={kind='target_interaction',landmark='gadget_c',auto=true},
            instruction='At Gadget C, the guide arms //pt use sortie-boss-skomora-v1 armed and automatically requests //sw so p port. Stack all six in melee range after arrival and select Skomora on Dolo; Tackle pulls first automatically.',
            warning='The successful Skomora damage/support policy is unchanged; only its opening is now an automatic Tackle-first handoff. Alt-P stops immediately and the guide will not repeatedly re-arm after that override.',
            detail={
                'The sustainable baseline is Chaos/Samurai, Barney\'s real three physical songs, Fury/Frailty, and Tackle Majesty healing.',
                'Tackle opens and holds hate. Smalls prioritizes status removal, Refresh/Haste, Dia, and emergency recovery.',
            },
        },
        {
            id='skomora_boss', area='BOSS C: SKOMORA',
            profile='sortie_boss_skomora_v1', profile_arm=true,
            objective='boss_skomora',
            reward={scope='ground_floor',label='Skomora reward chest'},
            completion={kind='all_temp_item',item='shard_g',auto=true},
            instruction='Select Skomora on Dolo; the armed runtime sends Tackle alone first, then releases all damage after his opening threat action. Spend TP quickly, keep all six stacked, remove Paralyze/Bind/Curse, and have Dolo open the reward chest.',
            warning='Three-minute damage check: Setting the Stage deals about 30,000 split among targets in range. Alt-P stops immediately; nothing prevents manual actions or an improvised recovery.',
            detail={
                'Regurgitated Swarm resets TP, so the profile fires at 1000. Skomora absorbs Dark damage.',
                'Optional manual optimizations from Umbra: Light Shot after Dia, Fire Shot, Impact, Absorb-TP, or Stun. None is required or awaited.',
            },
        },
        {
            id='return_device_c', area='BACK TO DEVICE C',
            automation={kind='sortie_superwarp',operation='port'},
            path={'gadget_c','c_gadget_east','c_gadget_south','gate_c1',
                'c_bottom_east','gate_c2','c_gate2_west','c_gate3_south',
                'gate_c3','c_gate3_west','c_device_south_turn','device_c'},
            completion={kind='landmark',landmark='device_c',auto=true},
            instruction='After Shard G is confirmed, the guide disarms combat and automatically requests //sw so p port at the arena Gadget. Follow the reverse point-by-point arrow to Device C.',
            warning='If the boss-room exit changes your position abruptly, ignore the temporary bearing until the exterior finishes loading, then use //exg wp if needed.',
        },
        {
            id='warp_device_a', area='TO DEVICE A',
            path={'device_c','device_a'},
            automation={kind='sortie_superwarp',operation='device_a'},
            completion={kind='landmark',landmark='device_a',auto=true},
            instruction='Gather at Device C. ExpeditionGuide automatically requests //sw so p a and resumes the arrow at Device A.',
            warning='Superwarp owns its normal validation/retry behavior. Manual warping and every other improvisation remain available.',
        },
        {
            id='a_objective_setup', area='A ACCESS SETUP',
            path={'a_device_east','a_east_north','a_east_bend','a_top_east',
                'a_gate3_west','a_mid_north','a_mid_south','a_gate2_east',
                'a_objective_camp'},
            profile='sortie_objective_a_magic_kill_v1',
            profile_arm=true,
            completion={kind='landmark',landmark='a_objective_camp',auto=true},
            instruction='Follow the arrow toward the upper A Abject Acuex. The guide automatically runs //pt use sortie-objective-a-magic-kill-v1 armed; select each Acuex on Dolo. Tackle pulls first, then all five burn at full speed.',
            warning='The profile automatically peels melee and assigns the final single-target Fire casts. If the traced camp is empty, improvise with the real corridor; no movement or target choice is gated.',
            detail={
                'Acuex are the preferred workbook targets and are weak to Fire. The boss profile stays inert until all six qualifying kills are done.',
                'Open A2/A3 if the route encounters them closed; the permanent A key already exists on all six.',
            },
        },
        {
            id='a_shard', area='A SHARD 0/3', waypoint='a_objective_camp',
            profile='sortie_objective_a_magic_kill_v1', profile_arm=true,
            objective='shard_a_magic',
            reward={scope='ground_floor',label='Shard A chest'},
            completion={kind='all_temp_item',item='shard_a',auto=true},
            instruction='Select three Abject Acuex in succession. Tackle claims first; five members burn, heavy lanes stop at 45%, all melee stops at 32%, and Smalls/Achoo repeatedly cast single-target Fire. Dolo opens Shard A.',
            warning='The runtime reports its observed last damage, but the chest and all-six Shard A evidence decide success. Alt-P never becomes locked out.',
        },
        {
            id='a_metal', area='A METAL 3/6', waypoint='a_objective_camp',
            profile='sortie_objective_a_magic_kill_v1', profile_arm=true,
            objective='metal_a_magic',
            reward={scope='ground_floor',label='Metal A chest'},
            completion={kind='all_temp_item',item='metal_a',auto=true},
            instruction='Select three more Abject Acuex; the armed profile repeats the full-speed burn-to-Fire handoff automatically. Dolo opens the Metal A chest.',
            warning='Metal A is intentionally required for this training route because it turns Taint into removable Poison. You may //exg skip and improvise, but recovery becomes much less forgiving.',
        },
        {
            id='travel_gadget_a', area='TO GADGET A',
            profile='sortie_boss_ghatjot_v1',
            path={'a_objective_camp','a_upper_west','a_gadget_bend','gadget_a'},
            completion={kind='landmark',landmark='gadget_a',auto=true},
            instruction='Follow the arrow west and around the northwest bend to Gadget A. The guide loads //pt use sortie-boss-ghatjot-v1 unarmed so support settles during travel.',
            warning='The public-map corridor points are provisional. Follow the real hallway and use //exg wp or //exg mark whenever needed.',
        },
        {
            id='ghatjot_stage', area='GADGET A', waypoint='gadget_a',
            profile='sortie_boss_ghatjot_v1',
            profile_arm=true,
            automation={kind='sortie_superwarp',operation='port'},
            completion={kind='target_interaction',landmark='gadget_a',auto=true},
            instruction='At Gadget A, the guide arms //pt use sortie-boss-ghatjot-v1 armed and automatically requests //sw so p port. Stack in melee range, place Tackle in front, and select Ghatjot on Dolo; Tackle pulls first automatically.',
            warning='Confirm the automatic WS list is Savage Blade, Exenterator, and Black Halo only. Alt-P remains immediate and persistent.',
            detail={
                'Tackle opens with Flash/Provoke and tries to keep hate. Smalls and Kick remove Poison immediately whenever it lands.',
                'No Water, Water Shot, Leaden Salute, Distortion, or Darkness. Manual Fire Shot and Light Shot remain optional.',
            },
        },
        {
            id='ghatjot_boss', area='BOSS A: GHATJOT',
            profile='sortie_boss_ghatjot_v1', profile_arm=true,
            objective='boss_ghatjot',
            reward={scope='ground_floor',label='Ghatjot reward chest'},
            completion={kind='all_temp_item',item='shard_e',auto=true},
            instruction='Select Ghatjot on Dolo; the armed runtime sends Tackle alone first, then releases all damage after his opening threat action. Remove every Poison quickly and have Dolo open the reward chest after the kill.',
            warning='ABSOLUTELY NO WATER DAMAGE. The selected automatic WS mix cannot make Distortion or Darkness among itself. Alt-P and every manual recovery action remain available.',
        },
        {
            id='complete', area='TWO BOSSES COMPLETE',
            completion={kind='all_temp_items',auto=true,items={
                'shard_g','shard_e',
            }},
            instruction='Skomora and Ghatjot are complete and combat is automatically disarmed. Leave normally and spend the remaining time on any objective you choose.',
            warning='This training route is finished. It never restricts salvage, exploration, or improvisation after the two proofs.',
        },
    },
}
