return {
    schema=1,id='sortie-boss-leshonn-v1',version='1.1.0',
    policy_id='pt-sortie-leshonn',label='Sortie boss B: Leshonn non-REMA proof',
    aliases={'lesh','leshonn','sortie-leshonn','boss-b'},
    runtime_owns_pull=true,
    -- Explicit recovery profile only. sortie-main-v1 owns automatic Sortie
    -- target routing so this profile can never replace it on a target packet.
    members={
        Dolomedes={main_job='COR',sub_jobs={'DNC','NIN','DRK'}},
        Tackleberry={main_job='PLD',sub_jobs={'SCH','WAR','BLU','WHM'}},
        Kickpuncher={main_job='DNC',sub_jobs={'WAR','NIN','DRG'}},
        Barneystinson={main_job='BRD',sub_jobs={'WHM','NIN','DRK'}},
        Smalls={main_job='RDM',sub_jobs={'WHM','BLM','DRK'}},
        Achoo={main_job='GEO',sub_jobs={'WHM','BLM','DRK'}},
    },
    roles={route_leader='Dolomedes',tank='Tackleberry',
        manual_puller='Tackleberry',target_caller='Dolomedes',
        primary_healer='Tackleberry',backup_healer='Kickpuncher',
        emergency_healer='Smalls'},
    combat={leader='Dolomedes',puller='Tackleberry',movement='mobile',
        attackers={'Dolomedes','Tackleberry','Kickpuncher',
            'Barneystinson','Smalls','Achoo'},
        targeters={'Dolomedes','Tackleberry','Kickpuncher',
            'Barneystinson','Smalls','Achoo'},
        priority_attackers={},target_exclusions={}},
    support={
        cor={rolls={'chaos','samurai'}},
        brd={preset='magicboss',target_source='Tackleberry',healbot='off'},
        rdm={preset='sortieacuex',target_source='Tackleberry',
            haste={'Tackleberry','Dolomedes','Kickpuncher','Smalls'},
            refresh={'Smalls','Achoo','Tackleberry'},
            phalanx={'Tackleberry','Dolomedes'},defense={},healbot='off'},
        geo={mode='leanmanaged',zerg=false,indi='Fury',geo='Frailty',
            entrust='Refresh',entrustee='Smalls',
            combat_entrust_only=false,healbot='off'},
        pld={preset='manualsc',leader='Dolomedes',
            native_buffs=false,native_tank=false},
        dnc={preset='physical',target_source='Tackleberry'},
    },
    offense={
        Dolomedes={weapon_mode='DualSavage',ws='Savage Blade',tp=1000},
        Tackleberry={weapon_mode='Naegling',ws='Savage Blade',tp=1000},
        -- Dancing Edge after Savage Blade/Black Halo can create Wind-aligned
        -- Detonation. Keep Kick's melee active but his automatic WS off in v1.
        Kickpuncher={weapon_mode='Tauret',ws='Dancing Edge',tp=1000,
            automatic=false,disable_native_autows=true},
        Barneystinson={weapon_mode='Naegling',ws='Savage Blade',tp=1000},
        Smalls={weapon_mode='Maxentius',ws='Black Halo',tp=1000},
        Achoo={weapon_mode='Maxentius',ws='Black Halo',tp=1000},
    },
    manual_actions={},safety={reraise=true},
    advisories={
        'Explicit recovery profile only; sortie-main-v1 owns automatic target handling. If deliberately loaded, Tackle is preferred for first threat and an existing party claim releases all six.',
        'Shard B is required. Metal B is useful but not mandatory: it blocks thunder-hand autoattack Stun and wind-hand Gravity, not Chokehold itself.',
        'Thunder hands copy enfeebles with Zap. BRD, RDM, and PLD automation therefore schedule no Elegy, Dia, Flash, or other persistent debuff; GEO bubbles and DNC Box Step are the approved exceptions.',
        'Wind hands steal buffs with Chokehold. Native PLD buff/tank automation is disabled and manualsc never schedules Sentinel; support maintenance replaces ordinary stolen buffs automatically.',
        'Matching Wind or Lightning damage, including matching skillchains, can heal Leshonn. Savage Blade and Black Halo are the automatic WS set because they do not chain with one another; Kick melees but holds Dancing Edge in this first proof.',
        'Tackle alone faces Leshonn from the front. Dolo, Kick, Barney, Smalls, and Achoo must stand behind or on a rear flank. Positioning is an operator instruction, never an automation gate, and manual improvisation is never filtered.',
    },
}
